# Generated by Django 3.2.7 on 2021-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='body',
            field=models.TextField(default='', max_length=254),
        ),
    ]
