# Generated by Django 3.2.7 on 2021-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactform_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
