# Generated by Django 3.2.7 on 2021-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactform_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='body',
            field=models.TextField(default='', max_length=254),
        ),
    ]
