# Generated by Django 3.2.7 on 2021-09-12 09:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_modelblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelblog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
