# Generated by Django 3.2.7 on 2021-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_modelblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='intro',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
